---
Resources:
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: demo
      # todo: this has no effect, see readme for setting this via CLI
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1
          AttributeType: S
        - AttributeName: gsi2
          AttributeType: S
        - AttributeName: ttl
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      LocalSecondaryIndexes:
        - IndexName: lsi1
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1
              KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: gsi1
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: sk
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
        - IndexName: gsi2
          Projection:
            ProjectionType: ALL
          KeySchema:
            - AttributeName: gsi2
              KeyType: HASH
